<a href="https://colab.research.google.com/github/STbim/Object-detection/blob/master/basic_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello")

Hello


In [3]:
# Dictionary
# key : value
thisdict ={"brand" : "subaru", "year" : 2022}
print(thisdict["brand"])
print(thisdict["year"])


subaru
2022


In [4]:
# Condition
a = 500
b= 50
if b > a:
  print("b is greater than a")
elif a > b:
  print("a is greater than b")
else:
  print(" a and b are equal")

a is greater than b


In [7]:
# while loop
i = 3 
while i < 8:
  print(i)
  i = i + 2

3
5
7


In [9]:
# object
# [1] คุณสมบัติ (Attribute) [2] ฟังก์ชั่นการทำงาน (Method)
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age 
  def eat(selt):
    print("I can eat now")

p1 = Person("Sarawut", 26)
print(p1.name)
print(p1.age)
p1.eat()

    

Sarawut
26
I can eat now


In [14]:
# การเรียกใช้ ไลบรารี่
import numpy as np

# numpy array
arr = np.array(50)
print(arr)

arr = np.array([1, 2, 3, 4, 5])
print(arr)

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)
print(arr.shape)

50
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
2
(2, 3)
